;;; editor/meow/autoload/bindings-engrammer.el -*- lexical-binding: t; -*-
;;;###autoload
(defconst meow-cheatsheet-layout-engrammer
  '((<TLDE> "[" "{")
    (<AE01> "1" "!")
    (<AE02> "2" "@")
    (<AE03> "3" "#")
    (<AE04> "4" "$")
    (<AE05> "5" "%")
    (<AE06> "6" "^")
    (<AE07> "7" "&")
    (<AE08> "8" "*")
    (<AE09> "9" "()")
    (<AE10> "0" ")")
    (<AE11> "[" "{")
    (<AE12> "]" "}")
    (<AD01> "b" "B")
    (<AD02> "y" "Y")
    (<AD03> "o" "O")
    (<AD04> "u" "U")
    (<AD05> "'" "\"")
    (<AD06> ";" ":")
    (<AD07> "l" "L")
    (<AD08> "d" "D")
    (<AD09> "w" "W")
    (<AD10> "v" "v")
    (<AD11> "z" "Z")
    (<AD12> "+" "=")
    (<AC01> "c" "C")
    (<AC02> "i" "i")
    (<AC03> "e" "E")
    (<AC04> "a" "A")
    (<AC05> "," "<")
    (<AC06> "." ">")
    (<AC07> "h" "H")
    (<AC08> "t" "T")
    (<AC09> "s" "S")
    (<AC10> "n" "N")
    (<AC11> "q" "Q")
    (<AB01> "g" "G")
    (<AB02> "x" "X")
    (<AB03> "j" "J")
    (<AB04> "k" "K")
    (<AB05> "-" "_")
    (<AB06> "/" "?")
    (<AB07> "r" "R")
    (<AB08> "m" "M")
    (<AB09> "f" "f")
    (<AB10> "p" "P")
    (<BKSL> "-" "_")))


;;;###autoload
(defun +meow--setup-engrammer ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-engrammer)
  (meow-motion-overwrite-define-key
   ;; 'j' and 'k' are suggested to be bound to `meow-next' and `meow-prev', but
   ;; these deactivate the region, which is not helpful unless we're in normal
   ;; state.
   ;; TODO PR in suggested bindings
   '("n" . next-line)
   '("p" . previous-line)
   '("<escape>" . ignore))
  (meow-leader-define-key
   ;; ;; The suggested bindings would have allowed us to use 'SPC j' and 'SPC k'
   ;; ;; to run whatever commands were originally mapped to 'j' and 'k' while in
   ;; ;; Motion state. But our bindings make SPC k the prefix for
   ;; ;; `doom-leader-code-map', so that won't work. Nevertheless, we leave
   ;; ;; those bindings here anyway.
   ;; SPC j/k will run the original command in MOTION state
   ;; (because we set `meow-motion-remap-prefix' to "C-")
   '("j" . "C-j")
   '("k" . "C-k")
   ;; Use SPC (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("1" . meow-expand-1)
   '("2" . meow-expand-2)
   '("3" . meow-expand-3)
   '("4" . meow-expand-4)
   '("5" . meow-expand-5)
   '("6" . meow-expand-6)
   '("7" . meow-expand-7)
   '("8" . meow-expand-8)
   '("9" . meow-expand-9)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("/" . meow-visit)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("C" . meow-cancel)
   '("d" . meow-prev)
   '("D" . meow-prev-expand)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("F" . meow-find-ref)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-join)
   '("J" . meow-join-sexp)
   '("k" . meow-kill)
   '("K" . meow-keypad)
   '("l" . meow-line)
   '("L" . meow-goto-line)
   '("m" . meow-mark-word)
   '("M" . meow-mark-symbol)
   '("n" . meow-next)
   '("N" . meow-next-expand)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("P" . meow-yank-pop)
   '("q" . meow-quit)
   '("Q" . meow-search)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-right)
   '("S" . meow-right-expand)
   '("t" . meow-next)
   '("T" . meow-next-expand)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-till)
   '("V" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-delete)
   '("X" . meow-backward-delete)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("\\" . qutoed-insert)
   '("<escape>" . ignore)
   )
  )
